---
# vars file for docker
container_count: 2
default_container_name: docker
default_container_image: nginx:latest
default_container_command: sudo apt update && sleep 1

packages:
  - tree
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
