---
# tasks file for deployment

- name: Check and output OS version
  debug: var=ansible_os_family
- block:
    - name: Install nginx
      apt:
        name: apache2
        state: latest
    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Restart Apache2 service
      service:
        name: apache2
        state: restart
    - name: Delete Apache2
      apt:
        name: apache2
        state: absent
  when: ansible_os_family == "Debian"
