---
# handlers file for docker

# restart docker service
- name: Restart Docker
  service: name=docker state=restarted

  # give access to user
- name: Give Access to user
  shell: newgrp docker && usermod -aG docker dark
