pipeline {
    agent any
    parameters {

    }

    environment {
        
    }
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
