pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '10'))
    }

    stages {
        stage('Build') {
            
            steps {
                echo 'git status'
                echo 'Start Ansible playbook..'
                sh 'git clone -b test git@github.com:Black872/ProjectW.git ~/gclone'
                sh 'ls -la'
                echo 'Complete.'
                echo '------------------------'
                sh 'rm -rf ~/gclone/*'
                sh 'rm -rf .git'
                echo 'Build Id: ${BUILD_ID}'
                
            
            }

        }
        

    }
}
