---
- name: testbook
  hosts: DEV
  become: true

  tasks:
    - name: libc6 check
      shell:
        cmd: apt show -a libc6
      register: lib6output
    - name: Debug libc6
      debug:
        msg: "{{ lib6output.stdout_lines[1] }}"
    - name: install libc6 2.35
      shell:
        cmd: apt install libc6="2.35-0ubuntu3.4"
